### ISSUE TITLE
Epic: Add reviews 

### ISSUE THREAD

**Issue by Baagi** [MaggieYang57/CSC308-TeamB#11]
## User Story

**As a** person who looks at reviews before considering anything

**I'd like to** I want to read reviews about the hikes from past hikers 

**so that** I can see other people’s experience and their hiking experiences.

## To-do

- [x] Research how we want to store the reviews in the database.  Estimate 1-2 hours.
   - Potentially create a new collection in the database and link the reviews to the individual hikes. 
- [x] Setup `hike/review` API endpoints for the reviews. Estimate 2-4 hours.
   - GET method to get all the reviews.  Estimate 1 hour. #43
   - POST method to post a review. Estimate 1 hour. #44
   - DELETE method to delete a review. Estimate 1 hour. #45 
- [ ] Figure out and design how the reviews will display on front-end. Estimate 1-2 hours. #57 

## Testing

- Check if the data is added/updated/deleted on the back end

## Estimate

Time: 5-8 hours.

**Comment by Baagi** [comment]
I feel like this could be an Epic.

**Comment by Baagi** [comment]
Update the description for the Sprint 2.

**Comment by Baagi** [comment]
Additional issue: https://github.com/MaggieYang57/CSC308-TeamB/issues/55 to soft delete reviews.
